version: '3'
services:
    nginx:
        image: nginx:latest
        ports:
            - '2501:80'
        volumes:
            - .:/code
            - ./config/docker/nginx/nginx.conf:/etc/nginx/nginx.conf

    postgis:
        image: postgis/postgis:13-3.1
        ports:
            - '2502:5432'
        environment:
            POSTGRES_USER: johnnoel
            POSTGRES_PASSWORD: johnnoel
